name: Deploy to AWS Lambda (v2)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Quality and Security Gate
        run: |
          pip install flake8 bandit pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          bandit -r . -ll
          pytest

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::330552995255:role/v2-gha-deploy-role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: 330552995255.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: v2-agnostic-lambda-core
          IMAGE_TAG: latest
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --push .
      
      - name: Deploy and Set Version
        run: |
            # 1. The code (container) refresh
            aws lambda update-function-code \
              --function-name v2-agnostic-lambda \
              --image-uri ${{ steps.login-ecr.outputs.registry }}/v2-agnostic-lambda-core:latest
            # 2. PRO: Wait for AWS to complete the code update
            echo "Waiting for Lambda update to complete..."
            aws lambda wait function-updated --function-name v2-agnostic-lambda
             # 3. A version (Commit SHA) setup environment variable
             SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
             aws lambda update-function-configuration \
                --function-name v2-agnostic-lambda \
                --environment "Variables={VERSION=$SHORT_SHA}"

      - name: Smart Smoke Test (Version Validation)
        run: |
          EXPECTED_VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Waiting for version: $EXPECTED_VERSION"
          
          # Maximum 20 try wtih 2sec wait
          for i in {1..20}; do
            RESPONSE=$(curl -s ${{ secrets.LAMBDA_URL }})
            ACTUAL_VERSION=$(echo $RESPONSE | python3 -c "import sys, json; print(json.load(sys.stdin).get('version', ''))")
            
            echo "Check $i: Actual version in cloud: '$ACTUAL_VERSION'"

            if [ "$ACTUAL_VERSION" == "$EXPECTED_VERSION" ]; then
              echo "Success: The new version: ($ACTUAL_VERSION) is online!"
              exit 0
            fi
            
            echo "Old version running, still waiting..."
            sleep 2
          done
          
          echo "Error: Time-out. Lambda is not updated to $EXPECTED_VERSION version"
          exit 1  
